### PR TITLE
Implement QT interface

### PR DESCRIPTION
**Pull request by sneakyweasel**
- Implements interface used by quantum-tensors
- Working towards rewriting performance issues in QT-QG2

### CODE REVIEW

**Comment by stared** [comment]
I cannot merge that for fundamental reasons.

The version here need to base on a version `quantum-tensor` NOT the current `master`.

**Comment by sneakyweasel** [comment]
The latest QT wasn't converted to a npm package I can reference. How do you want to proceed?

**Comment by stared** [comment]
Work on this branch. I will merge only after we release a new stable version of QT, after changes.

**Comment by stared** [comment]
See #226 instead.

**Pull request closed without merging**
