### PR TITLE
limit access to the game

### PR DESCRIPTION
**Pull request by Frizi**
Disable access to proper game levels, keep it under a feature flag.

This is mostly a stopgap. The flag should eventually be replaced with more proper access control and a compile time switch. We will need to add some demo levels.

As an interesting model of paid game that is also fully open source - see https://github.com/tobspr/shapez.io

### CODE REVIEW

**Comment by stared** [comment]
In such PRs a screenshot would be very desirable! :)

**Comment by Frizi** [comment]
The only real visual difference is the disabled "play game" button, and a missing "levels" entry in the in-game menu.

image

**Comment by stared** [comment]
This visual looks more like an error, than intended. 
Maybe full opacity, but with gray and "coming soon"?

**Comment by Frizi** [comment]
That's up to @KlemKlem, I have just used the "disabled" style as it it already was. I agree that opacity might not be the best choice here though.

**Comment by Frizi** [comment]
I've moved the buttons to always be below the logo, but i'll leave the design of potential "coming soon" text to @KlemKlem :)

I think now the opacity works fine as a disabled state.

image

**Comment by KlemKlem** [comment]
The inactive button should have different colors (not opacity, it doesn't work well on this background):
#6c508c main body, #beabd8 text, #3e2954 underline

They might still need to be a bit brighter, but I can change it later.

**Comment by Frizi** [comment]
Changed according to above colors
image

**Pull request closed without merging**
